### ISSUE TITLE
The servers list has no indication of server's status

### ISSUE THREAD

**Issue by utkarsh867** [deploifai/vscode-deploifai#10]
There must be an indicator/tag that can show server status. There are edge cases, for example, when the server is still creating, or when the server is stopped, that the extension will malfunction.

**Comment by 98sean98** [comment]
I propose the following logic of handling training server cloud orchestration `status` and running `state`.

| status | should show item in tree | icon to show in item | description | tooltip |
|---|----|----|---|---|
| DEPLOY_SUCCESS | yes | `vm-connect`  | see table below | see table below |
| DEPLOYING | yes | `pulse` | "deploying" | "Please wait for a few minutes" |
| DESTROYING | yes | `pulse` | "destroying" | "Training server is being destroyed, remote connection is no longer allowed" |
| all other states like DEPLOY_ERROR, DESTROY_ERROR | no | - | - | - |

Assuming that the `status === TrainingStatus.DEPLOY_SUCCESS`, we further handle what to do with the server's running `state`:

| state | description | tooltip |
| --- | --- | --- |
| RUNNING | nothing | "Click to open a remote connection" |
| SLEEPING | "sleeping" | "Click to start server, which will take a few minutes" |
| STARTING | "starting" | "Server is starting, please wait for a few minutes" |
| STOPPING | "stopping" | "Server is stopping, remote connection is not allowed until it is re-started" |

See [microsoft/vscode-icons](https://github.com/microsoft/vscode-icons) repo for available themed icons.

**Comment by 98sean98** [comment]
The UI looks a little bit like this, to try to convey information about each training server to the user.

<img width="435" alt="Screenshot 2023-09-12 at 6 27 01 PM" src="https://github.com/deploifai/vscode-deploifai/assets/22276614/2f3781d9-456f-4c37-90d6-675cf57f5c43">

**Comment by 98sean98** [comment]
According to a vscode extension guide, it is actually not recommended to fire commands when a tree item is clicked. Instead, we could use action buttons.

**Comment by 98sean98** [comment]
<img width="476" alt="Screenshot 2023-09-13 at 3 34 38 PM" src="https://github.com/deploifai/vscode-deploifai/assets/22276614/495b5e54-dd24-4534-a53b-38687b82e82c">

This is the look and feel I've come up with.
